services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports: 
      - "80:80"
    networks:
      - internal      
    container_name: nginx
  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    networks:
      - internal
    volumes:
      - ./laravel/images:/var/www/html/public/images
    container_name: php
    expose:
      - "9000"
  mysql:
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    container_name: db
    restart: always
    image: mysql:latest
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASS: 'user'
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - internal
networks:
  internal:
    driver: bridge