services:
  mysql:
      build: 
        context: .
        dockerfile: Dockerfile-sql
      container_name: db
      restart: always
      platform: linux/x86_64
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: 'root'
        MYSQL_USER: 'user'
        MYSQL_PASS: 'user'
      volumes:
        - ./db-data:/var/lib/mysql
      networks:
        - internal
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
    networks:
      - internal
    volumes:
      - ./laravel/images:/var/www/html/public/images
    container_name: php
    expose:
      - "9000"
networks:
  internal:
    driver: bridge