name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    needs: tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Generate .env file
      run: |
        cp .env.example .env
        sed -i "s/DB_HOST=.*/DB_HOST=${{ secrets.DB_HOST }}/" .env
        sed -i "s/DB_DATABASE=.*/DB_DATABASE=${{ secrets.DB_DATABASE }}/" .env
        sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/" .env

    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKER_PASS: ${{ secrets.DOCKERHUB_PASS }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mstermigol/laravel-apache:latest

    - name: Docker Push
      run: docker push mstermigol/laravel-apache


